config/routes.rb
OnlineBags::Application.routes.draw do
  resources :bags

end

app/models/bag.rb
class Bag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  # GET /bags
  # GET /bags.xml
  def index
    @bags = Bag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bags }
    end
  end

  # GET /bags/1
  # GET /bags/1.xml
  def show
    @bag = Bag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bag }
    end
  end

  # GET /bags/new
  # GET /bags/new.xml
  def new
    @bag = Bag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bag }
    end
  end

  # GET /bags/1/edit
  def edit
    @bag = Bag.find(params[:id])
  end

  # POST /bags
  # POST /bags.xml
  def create
    @bag = Bag.new(params[:bag])

    respond_to do |format|
      if @bag.save
        format.html { redirect_to(@bag, :notice => 'Bag was successfully created.') }
        format.xml  { render :xml => @bag, :status => :created, :location => @bag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bags/1
  # PUT /bags/1.xml
  def update
    @bag = Bag.find(params[:id])

    respond_to do |format|
      if @bag.update_attributes(params[:bag])
        format.html { redirect_to(@bag, :notice => 'Bag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bags/1
  # DELETE /bags/1.xml
  def destroy
    @bag = Bag.find(params[:id])
    @bag.destroy

    respond_to do |format|
      format.html { redirect_to(bags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/views/bags/_form.html.erb
<%= form_for(@bag) do |f| %>
  <% if @bag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bag.errors.count, "error") %> prohibited this bag from being saved:</h2>

      <ul>
      <% @bag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <!-- <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div> -->
 <table>
   <tr>
     <td valign="top"></td>
     <td valign="top"></td>
   </tr>
   <tr>
   <div class="field">
       <td valign="top"> <%= f.label :name %></td>
       <td valign="top"><%= f.text_field :name %></td>
      </div>
   </tr>
      <tr>
        <div class="field">
           <td valign="top"><%= f.label :description %></td>
           <td valign="top"><%= f.text_area :description %></td>
        </div>
   </tr>
      <tr>
         <div class="field">
           <td valign="top"><%= f.label :quantity %></td>
           <td valign="top"><%= f.text_field :quantity %></td>
         </div>
   </tr>
      <tr>
         <div class="field">
           <td valign="top"><%= f.label :image_url %></td>
           <td valign="top"><%= f.text_field :image_url %></td>
         </div>
   </tr>
      <tr>
         
           <td valign="top">&nbsp;</td>
           <td valign="top">
               <div class="actions">
                <%= f.submit %>
              </div>
           </td>
         
   </tr>
</table>

<% end %>

app/views/bags/edit.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Online Bags</title>
</head>

<body>
<div id="main_div" >
<table width="100%" height="517" cellpadding="0" cellspacing="0" style="border:none ">
<tr>
    <td height="90" colspan="2" valign="middle">
		<span class="style7">ONLINE BAG <span class="style9"><span class="style11">S</span><span class="style10"> Limited</span> </span></span>
    <td width="199" rowspan="2" valign="top" style="margin-top:0 ">
	  	<img src="../images/Guitar.jpg" width="100%" height="250" />
    </tr>
<tr>
  <td width="147" height="401" valign="top">
    Menu Here

  <td width="520" valign="top">
    <h1>Editing bag</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @bag %> |
    <%= link_to 'Back', bags_path %>

  </tr>
  <tr>
    <td height="24" colspan="3" style="border-top:#000000 thin solid; text-align:center ">&copy; Online Bags 2010</td>
  </tr>
</table>
</div>
</body>
</html>

app/views/bags/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Online Bags</title>
</head>

<body>
<div id="main_div" >
<table width="100%" height="517" cellpadding="0" cellspacing="0" style="border:none ">
<tr>
    <td height="90" colspan="2" valign="middle">	
		<span class="style7">ONLINE BAG <span class="style9"><span class="style11">S</span><span class="style10"> Limited</span> </span></span>
    <td width="199" rowspan="2" valign="top" style="margin-top:0 ">
	  	<img src="images/Guitar.jpg" width="100%" height="250" />
    </tr>
<tr>
  <td width="147" height="401" valign="top">
    Menu Here
    
  <td width="520" valign="top">
<h1>Available bags in the System</h1>

<table width="100%">
  <tr>
    <!-- <th style="text-align:left">Id</th> -->
    <th  style="text-align:left">Bags</th>
    <th  style="text-align:left">Name</th>
    <th  style="text-align:left">Description</th>
    <th style="text-align:left">Quantity</th>
    <th style="text-align:left" colspan="3">To Do</th>
  </tr>

<% @bags.each do |bag| %>
  <tr>
    <!-- <td><%= bag.id %></td> -->
    <td valign="top" width="10%"><img src="../images/<%= bag.image_url %>" width="100%" height="50" /></td>
    <td valign="top" width="15%"><%= bag.name %></td>
    <td valign="top"><%= bag.description %></td>
    <td valign="top"><%= bag.quantity %></td>
    <td valign="top"><%= link_to 'Show', bag %></td>
    <td valign="top"><%= link_to 'Edit', edit_bag_path(bag) %></td>
    <td valign="top"><%= link_to 'Remove', bag, :confirm => 'Are you sure you want to remove the bag from the system?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add a New Bag', new_bag_path %>

  </tr>
  <tr>
    <td height="24" colspan="3" style="border-top:#000000 thin solid; text-align:center ">&copy; Online Bags 2010</td>
  </tr>
</table>
</div>
</body>
</html>

app/views/bags/new.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Online Bags</title>
</head>

<body>
<div id="main_div" >
<table width="100%" height="517" cellpadding="0" cellspacing="0" style="border:none ">
<tr>
    <td height="90" colspan="2" valign="middle">
		<span class="style7">ONLINE BAG <span class="style9"><span class="style11">S</span><span class="style10"> Limited</span> </span></span>
    <td width="199" rowspan="2" valign="top" style="margin-top:0 ">
	  	<img src="../images/Guitar.jpg" width="100%" height="250" />
    </tr>
<tr>
  <td width="147" height="401" valign="top">
    Menu Here

  <td width="520" valign="top">
<h1>Add a new bag to existing stock</h1>

<%= render 'form' %>

<%= link_to 'Back', bags_path %>
  </tr>
  <tr>
    <td height="24" colspan="3" style="border-top:#000000 thin solid; text-align:center ">&copy; Online Bags 2010</td>
  </tr>
</table>
</div>
</body>
</html>

app/views/bags/show.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Online Bags</title>
</head>

<body>
<div id="main_div" >
<table width="100%" height="517" cellpadding="0" cellspacing="0" style="border:none ">
<tr>
    <td height="90" colspan="2" valign="middle">
		<span class="style7">ONLINE BAG <span class="style9"><span class="style11">S</span><span class="style10"> Limited</span> </span></span>
    <td width="199" rowspan="2" valign="top" style="margin-top:0 ">
	  	<img src="../images/Guitar.jpg" width="100%" height="250" />
    </tr>
<tr>
  <td width="147" height="401" valign="top">
    Menu Here

  <td width="520" valign="top">
    <h1>Selected Bag details</h1>
<p id="notice"><%= notice %></p>

<!-- <p>
  <b>Id:</b>
  <%= @bag.id %>
</p> -->

<p>
  <b>Name:</b>
  <%= @bag.name %>
</p>

<p>
  <b>Description:</b>
  <%= @bag.description %>
</p>

<p>
  <b>Quantity:</b>
  <%= @bag.quantity %>
</p>


<%= link_to 'Edit', edit_bag_path(@bag) %> |
<%= link_to 'Back', bags_path %>
  </tr>
  <tr>
    <td height="24" colspan="3" style="border-top:#000000 thin solid; text-align:center ">&copy; Online Bags 2010</td>
  </tr>
</table>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineBags</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>